# Generated by Django 3.0.1 on 2020-01-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewer', '0002_auto_20200106_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
