# Generated by Django 3.0.1 on 2020-01-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('brewer', '0003_auto_20200107_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer', to='accounts.Brewery'),
        ),
    ]
