# Generated by Django 3.0.1 on 2020-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewer', '0005_auto_20200108_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='flavor_note',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
