# Generated by Django 3.0.1 on 2020-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewer', '0006_auto_20200114_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='beer/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='genericbeer',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='g_beer/images/%Y/%m/%d'),
        ),
    ]
