# Generated by Django 3.0.1 on 2020-01-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
