# Generated by Django 3.0.1 on 2020-01-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenericBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abv', models.FloatField()),
                ('flavor', models.ManyToManyField(to='finder.Flavor')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abv', models.FloatField()),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Brewery')),
                ('flavor', models.ManyToManyField(to='finder.Flavor')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.Style')),
            ],
        ),
    ]
