# Generated by Django 3.0.1 on 2020-01-08 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brewer', '0004_auto_20200108_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_brewer', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, default='default/images/default.png', null=True, upload_to='profiles/images/%Y/%m/%d')),
                ('liked_beers', models.ManyToManyField(related_name='viewers', to='brewer.Beer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
