# Generated by Django 3.0.1 on 2020-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
