# Generated by Django 3.0.1 on 2020-01-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewer', '0005_auto_20200108_1334'),
        ('finder', '0002_remove_viewer_liked_beers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewer.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.Viewer')),
            ],
            options={
                'unique_together': {('user', 'beer', 'value')},
            },
        ),
    ]
