# Generated by Django 3.0.1 on 2020-01-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20200105_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
