# Generated by Django 3.0.1 on 2020-01-09 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brewer', '0005_auto_20200108_1334'),
        ('finder', '0004_auto_20200109_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('user', 'beer', 'like')},
        ),
        migrations.RemoveField(
            model_name='preference',
            name='value',
        ),
    ]
