# Generated by Django 3.0.1 on 2020-01-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_beer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
