# Generated by Django 3.0.1 on 2020-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_beer_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(blank=True),
        ),
    ]
