# Generated by Django 3.0.1 on 2020-01-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20200109_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
    ]
