# Generated by Django 3.0.1 on 2020-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_auto_20200105_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
