# Generated by Django 3.0.1 on 2020-01-09 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brewer', '0005_auto_20200108_1334'),
        ('finder', '0006_auto_20200109_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('user', 'beer', 'like')},
        ),
    ]
