# Generated by Django 3.0.1 on 2020-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_viewer_first_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profiles/images/%Y/%m/%d'),
        ),
    ]
